<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <Authors>Piotr Falkowski</Authors>
    <Description>Your everyday interfaces: IUnitOfWork, IRepository&lt;T&gt;, IFactory&lt;T&gt;, IValidatable, IValueEquatable&lt;T&gt;, IConverter&lt;TIn,TOut&gt;, IFormatter&lt;T&gt;. Nothing more, nothing less. netstandard2.0, MIT.</Description>
    <Copyright>Piotr Falkowski © 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/PFalkowski/StandardInterfaces</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PFalkowski/StandardInterfaces</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>IFactory;IValueEquatable;IValidatable;IRepository;IUnitOfWork;interfaces</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>3.2.0</Version>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
